### PR TITLE
Profile Update

### PR DESCRIPTION
**Pull request by Victor-chiemerie**
Add subsection for blogger on User profile  ✅
Edit profile UI  ✅
Report or block someone UI  ✅

### CODE REVIEW

**Comment by Needlinc** [comment]
Screenshot 2023-12-25 054143


Everything's Good!, Just correct the icons with the new design Yuuci made on figma

https://www.figma.com/file/MefVmu2pFqWvgmCZqotVVL/NEEDLINC?type=design&node-id=0%3A1&mode=design&t=0yRFI0gKK6mObnrs-1

**Comment by XRichardroidX** [comment]
Screenshot 2023-12-25 054143





Everything's Good!, Just correct the icons with the new design Yuuci made on figma

https://www.figma.com/file/MefVmu2pFqWvgmCZqotVVL/NEEDLINC?type=design&node-id=0%3A1&mode=design&t=0yRFI0gKK6mObnrs-1

**Comment by XRichardroidX** [comment]
Screenshot 2023-12-25 054856


**This is the new design**

**Comment by XRichardroidX** [comment]
On the Market place side of your profile page.

**Pull request merged**
